import logging
from typing import Any

from pyspark.sql.functions import col, datediff

from agents.base_agent import BaseAgent
from agents.contracts import AnalyticsAgentInput, AnalyticsAgentOutput
from processing.kpi_module import compute_operational_kpis

logger = logging.getLogger(__name__)


class AnalyticsAgent(BaseAgent):
    def __init__(self):
        super().__init__("AnalyticsAgent")

    def run(self, agent_input: AnalyticsAgentInput | Any):
        df = agent_input.df if isinstance(agent_input, AnalyticsAgentInput) else agent_input
        cached_df = None
        if "resolution_time_days" not in df.columns:
            df = df.withColumn(
                "resolution_time_days", datediff(col("closed_date"), col("created_date"))
            )

        if "sla_breach" not in df.columns:
            raise ValueError(
                "AnalyticsAgent requires an sla_breach column generated by the feature-engineering layer."
            )

        try:
            df = df.cache()
            df.count()
            cached_df = df
            logger.info("AnalyticsAgent: cached DataFrame for repeated operations")
        except Exception as e:
            logger.warning(f"AnalyticsAgent: caching failed: {e}")
        try:
            kpi_payload = compute_operational_kpis(df)
        finally:
            if cached_df is not None:
                try:
                    cached_df.unpersist(blocking=False)
                except Exception as e:
                    logger.warning(f"AnalyticsAgent: unpersist failed: {e}")

        return AnalyticsAgentOutput(
            status="success",
            data=kpi_payload,
            warnings=[],
            errors=[],
        )
